### ISSUE TITLE
The future of Novidia

### ISSUE THREAD

**Issue by deorth-kku** [PDModdingCommunity/PD-Loader#8]
Hello nastys: 
Does [this comment](https://github.com/PDModdingCommunity/PD-Loader/commit/d7dfc57192ce6dbfa4090fe44eef0111f36674f4) means there will be no more development for Novidia to support the future AMD drivers? Since the shader patch was never updated in the first place.
Thanks.

**Comment by somewhatlurker** [comment]
I don't believe anyone is actively working on adding support for the new drivers. The warning is just a reflection of current state though, and doesn't indicate future intention in either direction.
I might have a look and see what can be done eventually (probably not soon), but from what I've heard there are some fairly significant changes in how these archaic shaders are handled so I can't promise anything. I'm actually kinda hoping AMD might quietly fix some of it in the coming months, but that's just wishful thinking haha.

Fortunately, Mega Mix+ released for PC recently, which is a great way to get FT gameplay and PVs on PC with much less risk of being affected by this kind of change if you can buy it.

**Comment by nastys** [comment]
You can always run it on Linux with libGL.so (using LD_PRELOAD or progl) from a supported version of amdgpu-pro (and Novidia force-enabled), since it's just a user-space driver. Maybe you can do something similar with AMD's OpenGL implementation on Windows.

If you don't care about debug mode, then I also suggest playing MM+ instead, especially since you're on AMD.

**Comment by deorth-kku** [comment]
> Fortunately, Mega Mix+ released for PC recently, which is a great way to get FT gameplay and PVs on PC with much less risk of being affected by this kind of change if you can buy it.

I'm aware of the offical PC port since its release, but I'm just not in the mood for paying for the same game for the third time. Anyway I think I'm still gonna buy it in some steam sales some day.
I know everyone will leave this Non-offical version eventually but I just hope this project will not die so fast.





> You can always run it on Linux with libGL.so (using LD_PRELOAD or progl) from a supported version of amdgpu-pro (and Novidia force-enabled), since it's just a user-space driver. Maybe you can do something similar with AMD's OpenGL implementation on Windows.

My main gaming PC is on nvidia so this is not a major issue to me. And also the my AMD laptop is actually running arch linux (with amdgpu-pro to wine the game) and not used for gaming for its main propose. I'm just find myself free to dual-boot to windows and test the game with latest OpenGL-performance-enhanced driver another day. 
The true reason I'm opening this issue, as you may suspected, is to tell if there are still developers are willing to put some efforts to this project. 

Thank you both for your replies.

**Comment by nastys** [comment]
I know korenkonder has been working on a plugin called DivaGL. When/if released, it would make AFT compatible with any OpenGL 4.3-compatible driver.

Nearly everyone has moved to MM+ since its release, and AFT has not been updated for years, not even officially receiving the MM songs (which were released on PS4).
As for PD Loader, I plan to clean it up, fix bugs and movies on Linux, and separate convenience functions/plugins like PV customization and DivaWig from the main project, making it more for debugging and preservation purposes, rather than trying to emulate a PC release of PDFT, which now officially exists in the form of MM+.

**Comment by deorth-kku** [comment]
> I know korenkonder has been working on a plugin called DivaGL. When/if released, it would make AFT compatible with any OpenGL 4.3-compatible driver.
> 
> Nearly everyone has moved to MM+ since its release, and AFT has not been updated for years, not even officially receiving the MM songs (which were released on PS4). As for PD Loader, I plan to clean it up, fix bugs and movies on Linux, and separate convenience functions/plugins like PV customization and DivaWig from the main project, making it more for debugging and preservation purposes, rather than trying to emulate a PC release of PDFT, which now officially exists in the form of MM+.

Thx, that's a lot to looking forward to.
